# SPDX-License-Identifier: MIT
---
# Put handlers for tasks here.

# Example:
- name: podman handler to restart services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ __podman_services }}"
